from __future__ import annotations

import html
import json


def _number(value, digits: int = 3) -> str:
    return "—" if value is None else f"{float(value):.{digits}f}"


def build_session_report(session: dict, summary: dict, samples: list[dict], events: list[dict]) -> str:
    session_json = json.dumps(session, ensure_ascii=False).replace("</", "<\\/")
    samples_json = json.dumps(samples, ensure_ascii=False).replace("</", "<\\/")
    events_json = json.dumps(events, ensure_ascii=False).replace("</", "<\\/")
    cards = [
        ("Tổng frame", session["frame_count"]), ("FPS trung bình", _number(session["avg_fps"], 2)),
        ("EAR trung bình", _number(summary.get("ear_mean"))), ("MAR trung bình", _number(summary.get("mar_mean"))),
        ("PERCLOS cao nhất", _number(summary.get("perclos_max"))), ("Số lần chớp", summary.get("blink_count") or 0),
        ("Số lần ngáp", summary.get("yawn_count") or 0), ("Nhắm mắt lâu nhất", f'{_number(summary.get("max_eye_closure_seconds"), 2)} s'),
        ("Distraction cao nhất", _number(summary.get("distraction_score_max"), 1)), ("Số cảnh báo", len(events)),
    ]
    card_html = "".join(f'<article><strong>{html.escape(str(value))}</strong><span>{html.escape(label)}</span></article>' for label, value in cards)
    title = f"Báo cáo DMS — Phiên {session['id']}"
    return f"""<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title>
<style>
:root{{--bg:#0e1715;--panel:#172522;--line:#30413c;--ink:#eff7f3;--muted:#9aaba5;--green:#62c99f;--red:#ef7168;--amber:#e7ae55;--blue:#70a4ed}}
*{{box-sizing:border-box}}body{{margin:0;padding:28px;background:var(--bg);color:var(--ink);font:14px Arial,sans-serif}}main{{max-width:1500px;margin:auto}}header{{padding:24px;border-left:4px solid var(--green);background:var(--panel);border-radius:8px}}h1{{margin:0 0 7px;font:600 28px Georgia,serif}}header p,.muted{{color:var(--muted)}}.cards{{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin:18px 0}}article,.box{{background:var(--panel);border:1px solid var(--line);border-radius:8px}}article{{padding:17px}}article strong,article span{{display:block}}article strong{{font:600 24px Georgia,serif;color:var(--green)}}article span{{margin-top:6px;color:var(--muted);font-size:11px;text-transform:uppercase}}.charts{{display:grid;grid-template-columns:1fr 1fr;gap:16px}}.box{{padding:18px;margin-bottom:16px}}h2{{margin:0 0 5px;font:600 19px Georgia,serif}}canvas{{width:100%;height:300px;background:#101a18;border:1px solid var(--line);margin-top:14px}}.legend{{display:flex;gap:14px;flex-wrap:wrap;color:var(--muted);font-size:11px}}.legend i{{display:inline-block;width:9px;height:9px;margin-right:5px;border-radius:50%}}.toolbar{{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:15px 0}}input,select{{padding:9px 11px;background:#101a18;color:var(--ink);border:1px solid var(--line)}}button,a.button{{padding:9px 12px;border:0;background:#27795f;color:white;text-decoration:none;cursor:pointer}}.table-wrap{{overflow:auto;max-height:620px}}table{{width:100%;border-collapse:collapse;white-space:nowrap}}th,td{{padding:9px 11px;border-bottom:1px solid var(--line);text-align:left;font-size:12px}}th{{position:sticky;top:0;background:#101a18;color:var(--muted);cursor:pointer}}tr:hover td{{background:#1d302b}}.events{{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:10px}}.event{{padding:12px;background:#101a18;border-left:3px solid var(--amber)}}.event a{{color:var(--blue)}}@media(max-width:850px){{body{{padding:12px}}.charts{{grid-template-columns:1fr}}}}@media print{{body{{background:white;color:#111}}.box,article,header{{background:white;border-color:#bbb}}.toolbar{{display:none}}canvas{{background:white}}}}
</style></head><body><main><header><h1>{title}</h1><p>Tài xế: {html.escape(str(session.get('driver_name') or 'Chưa gán'))} ({html.escape(str(session.get('driver_external_id') or '—'))}) · Nguồn: {html.escape(str(session['source']))} · Trạng thái: {html.escape(session['status'])} · Bắt đầu: {html.escape(str(session.get('started_at') or '—'))}</p></header>
<section class="cards">{card_html}</section>
<section class="charts"><div class="box"><h2>Mệt mỏi theo thời gian</h2><div class="legend"><span><i style="background:#62c99f"></i>EAR</span><span><i style="background:#e7ae55"></i>MAR</span><span><i style="background:#70a4ed"></i>PERCLOS</span><span><i style="background:#ef7168"></i>Risk/100</span></div><canvas id="fatigue"></canvas></div>
<div class="box"><h2>Mất tập trung theo thời gian</h2><div class="legend"><span><i style="background:#62c99f"></i>Pitch/90</span><span><i style="background:#e7ae55"></i>Yaw/90</span><span><i style="background:#70a4ed"></i>Gaze X</span><span><i style="background:#ef7168"></i>Distraction/100</span></div><canvas id="attention"></canvas></div></section>
<section class="box"><h2>Sự kiện đã khử trùng lặp</h2><div id="events" class="events"></div></section>
<section class="box"><h2>Dữ liệu chi tiết theo mẫu</h2><p class="muted">Nhấn tên cột để sắp xếp. Các trạng thái độc lập không được cộng thành biểu đồ tròn.</p><div class="toolbar"><input id="search" placeholder="Tìm trạng thái/cảnh báo"><select id="limit"><option>50</option><option>100</option><option value="all">Tất cả</option></select><button onclick="renderTable()">Áp dụng</button><button onclick="window.print()">In / PDF</button><span class="muted">CSV và snapshot được tải từ dashboard đã đăng nhập.</span></div><div class="table-wrap"><table><thead id="head"></thead><tbody id="body"></tbody></table></div></section>
</main><script>const session={session_json};const samples={samples_json};const events={events_json};
const columns=['timestamp_seconds','frame_index','ear','mar','perclos','eye_closure_seconds','microsleep','blink_count','yawn_count','pitch','yaw','roll','gaze_x','gaze_y','distraction_score','cnn_drowsy','lstm_drowsy','phone','cigarette','seatbelt','risk_score','severity','warnings','processing_fps'];let sortKey='frame_index',sortAsc=true;
function esc(value){{return String(value??'—').replace(/[&<>"']/g,char=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[char]))}}
function lineChart(id,series){{const c=document.getElementById(id),dpr=devicePixelRatio||1,w=c.clientWidth,h=300;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.fillStyle='#101a18';x.fillRect(0,0,w,h);x.strokeStyle='#30413c';for(let i=0;i<5;i++){{let y=20+i*(h-40)/4;x.beginPath();x.moveTo(38,y);x.lineTo(w-12,y);x.stroke()}}series.forEach(s=>{{x.strokeStyle=s.color;x.lineWidth=2;x.beginPath();samples.forEach((p,i)=>{{let v=s.value(p);if(v==null)return;v=Math.max(0,Math.min(1,v));let px=38+i*(w-50)/Math.max(1,samples.length-1),py=h-20-v*(h-40);i?x.lineTo(px,py):x.moveTo(px,py)}});x.stroke()}})}}
lineChart('fatigue',[{{color:'#62c99f',value:p=>p.ear}},{{color:'#e7ae55',value:p=>p.mar}},{{color:'#70a4ed',value:p=>p.perclos}},{{color:'#ef7168',value:p=>p.risk_score/100}}]);lineChart('attention',[{{color:'#62c99f',value:p=>Math.abs(p.pitch||0)/90}},{{color:'#e7ae55',value:p=>Math.abs(p.yaw||0)/90}},{{color:'#70a4ed',value:p=>Math.abs(p.gaze_x||0)}},{{color:'#ef7168',value:p=>(p.distraction_score||0)/100}}]);
document.getElementById('events').innerHTML=events.length?events.map(e=>`<div class="event"><b>${{esc(e.event_type)}}</b><br>${{Number(e.timestamp_seconds||0).toFixed(2)}} s · Risk ${{esc(e.risk_score)}}<br>Trạng thái: ${{esc(e.review_status||'new')}}${{e.review_note?` · ${{esc(e.review_note)}}`:''}}</div>`).join(''):'Không có sự kiện.';
function renderTable(){{let q=document.getElementById('search').value.toLowerCase(),rows=samples.filter(r=>JSON.stringify(r).toLowerCase().includes(q));rows.sort((a,b)=>{{let x=a[sortKey],y=b[sortKey];return (x==null)-(y==null)||(x<y?-1:x>y?1:0)*(sortAsc?1:-1)}});let lim=document.getElementById('limit').value;if(lim!='all')rows=rows.slice(-Number(lim));document.getElementById('head').innerHTML='<tr>'+columns.map(c=>`<th onclick="sortBy(\'${{c}}\')">${{esc(c)}} ↕</th>`).join('')+'</tr>';document.getElementById('body').innerHTML=rows.map(r=>'<tr>'+columns.map(c=>`<td>${{esc(r[c])}}</td>`).join('')+'</tr>').join('')}}function sortBy(k){{sortAsc=sortKey===k?!sortAsc:true;sortKey=k;renderTable()}}renderTable();addEventListener('resize',()=>{{lineChart('fatigue',[{{color:'#62c99f',value:p=>p.ear}},{{color:'#e7ae55',value:p=>p.mar}},{{color:'#70a4ed',value:p=>p.perclos}},{{color:'#ef7168',value:p=>p.risk_score/100}}]);lineChart('attention',[{{color:'#62c99f',value:p=>Math.abs(p.pitch||0)/90}},{{color:'#e7ae55',value:p=>Math.abs(p.yaw||0)/90}},{{color:'#70a4ed',value:p=>Math.abs(p.gaze_x||0)}},{{color:'#ef7168',value:p=>(p.distraction_score||0)/100}}])}});
</script></body></html>"""
